//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emolyee
    {
        public int empolyeeId { get; set; }
        public string empolyeeName { get; set; }
        public Nullable<int> dep_Id { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual departemnt departemnt { get; set; }
        public virtual Login Login { get; set; }
    }
}
