//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class employeeContextEntites : DbContext
    {
        public employeeContextEntites()
            : base("name=employeeContextEntites")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<departemnt> departemnt { get; set; }
        public virtual DbSet<emolyee> emolyee { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
    }
}
